name: numo
description: "Numo — контроль трат и анализ личных финансов. Все платформы, современный UI."
publish_to: 'none'
version: 0.5.0+4

environment:
  sdk: ^3.9.0

dependencies:
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  http: ^1.6.0
  intl: any
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
